temperature_text="//span[@id='temperature']"
# least_priced_product ="//p[contains(text(),"+minimum_price+")]/following-sibling::button[@class='btn btn-primary']"
moisturizers_button = "//button[contains(text(),'Buy moisturizers')]"
price_of_all="//p[contains(text(),'Price')]"
sunscreens_button= "//button[contains(text(),'Buy sunscreens')]"
cart_button="//button[@class='thin-text nav-link']"
payment_button="//span[normalize-space()='Pay with Card']"